### ISSUE TITLE
show indicator on browser tab icon if own build fails (e.g. like slack shows new messages)

### ISSUE THREAD

**Issue by Ralf1108** [marcells/node-build-monitor#17]

**Comment by marcells** [comment]
I have to check, if it's easily possible determine the state of a build. But it's definitely possible to show an indicator, when an own build is processed.

**Comment by marcells** [comment]
In the latest version, you can now define a notification filter (regular expression). If this filter matches to any of the build properties (e.g. project name or user name), you will see the notification, otherwise it will be omitted. There is also a red overlay in the favicon, when the builds changed (the filter is applied here, too).

**Comment by Ralf1108** [comment]
awesome !! :-)
