### ISSUE TITLE
Teamcity integration broken with TC 10.0

### ISSUE THREAD

**Issue by Sauraus** [marcells/node-build-monitor#29]
In TC 10.x `var requestFinishedBuilds = makeRequest.bind(this, getFinishedBuildsUrl());`returns a correct URL and also a valid data set, however the monitor still reports 0 builds found, any ideas what this could be?

**Comment by marcells** [comment]
Hm, very strange. Do you see some information, when you activate the `debug` [flag](https://github.com/marcells/node-build-monitor/blob/master/app/config.json)?

**Comment by Sauraus** [comment]
Nothing :( just this: 
```
21:18:07 | Check for builds...
21:18:13 | 0 builds found....
```

**Comment by marcells** [comment]
I've currently no TC instance running. Do you think you can try to find out
the error with some console.log statements in the TeamCity.js service?

If not, I can try to reproduce it. But that could take a bit longer.
Currently there's a lot of work in my day job. 😉

Antek Baranski <notifications@github.com> schrieb am Do., 10. Nov. 2016,
22:19:

**Comment by Sauraus** [comment]
I will take a look at this yes.

**Comment by marcells** [comment]
Great, thank you!

Antek Baranski <notifications@github.com> schrieb am Do., 10. Nov. 2016,
22:27:

I will take a look at this yes.

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/marcells/node-build-monitor/issues/29#issuecomment-259812388>,
or mute the thread

**Comment by Sauraus** [comment]
Looks like the bug was caused by something `node` on my Raspberry Pi... :( The same code on OS X works out of the box.
